"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import sys
import dj_database_url
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
env_path = BASE_DIR / ".env"

AUTH_USER_MODEL = "core.User"

if env_path.exists():
    load_dotenv(env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!

ENVIRONMENT = os.getenv("ENVIRONMENT")

# allows all hosts in development, but only specific hosts in production
if (ENVIRONMENT or "").lower() == "development":
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL)
}

# REST FRAMEWORK
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ]
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite default port
    "http://localhost:3000",  # React default port
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
]

# Add production frontend URL from env var (e.g. https://your-app.vercel.app)
_extra_cors = os.getenv("CORS_ALLOWED_ORIGINS")
if _extra_cors:
    CORS_ALLOWED_ORIGINS += [o.strip() for o in _extra_cors.split(",") if o.strip()]

# Allow all Vercel preview deploy URLs
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]

CORS_ALLOW_CREDENTIALS = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- File uploads: S3-compatible storage (Cloudflare R2, Supabase Storage, etc.) ---
# Provider-neutral env vars: S3_ACCESS_KEY, S3_SECRET_KEY, S3_BUCKET, S3_ENDPOINT, S3_PUBLIC_URL.
# Falls back to legacy SUPABASE_* names during migration.
AWS_ACCESS_KEY_ID = (
    os.getenv("S3_ACCESS_KEY") or os.getenv("SUPABASE_S3_ACCESS_KEY") or ""
).strip() or None
AWS_SECRET_ACCESS_KEY = (
    os.getenv("S3_SECRET_KEY") or os.getenv("SUPABASE_S3_SECRET_KEY") or ""
).strip() or None
AWS_STORAGE_BUCKET_NAME = (
    os.getenv("S3_BUCKET") or os.getenv("SUPABASE_STORAGE_BUCKET") or ""
).strip() or None
AWS_S3_ENDPOINT_URL = (
    os.getenv("S3_ENDPOINT") or os.getenv("SUPABASE_S3_ENDPOINT") or ""
).strip() or None
AWS_S3_REGION_NAME = (os.getenv("AWS_S3_REGION_NAME") or "auto").strip() or "auto"
AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = None
AWS_S3_ADDRESSING_STYLE = "path"

# Public URL prefix for serving files. Differs by provider:
#   R2:       https://pub-<hash>.r2.dev   (or custom domain)
#   Supabase: https://<project>.supabase.co/storage/v1/object/public/<bucket>
# If unset, falls back to the legacy Supabase-style path on the endpoint.
_s3_public_url = (os.getenv("S3_PUBLIC_URL") or "").strip().rstrip("/") or None

_s3_fully_configured = bool(
    AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME and AWS_S3_ENDPOINT_URL
)
_is_development = (ENVIRONMENT or "").strip().lower() == "development"
_s3_media_explicit = (os.getenv("USE_S3_MEDIA") or "").strip().lower() in ("1", "true", "yes")

USE_S3_STORAGE = _s3_fully_configured and (
    (_is_development and _s3_media_explicit) or (not _is_development)
)

if USE_S3_STORAGE:
    INSTALLED_APPS += ["storages"]
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    if _s3_public_url:
        MEDIA_URL = f"{_s3_public_url}/"
        AWS_S3_CUSTOM_DOMAIN = _s3_public_url.split("://", 1)[-1]
    else:
        MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/object/public/{AWS_STORAGE_BUCKET_NAME}/"
else:
    MEDIA_ROOT = BASE_DIR / "media"
    MEDIA_URL = "/media/"