--
-- PostgreSQL database dump
--

\restrict SwlyxFxAiUt4GvrK6J2wgiCa7i6S1zHAYScdfKD54DomabNUBIKr4cpbNn91JWM

-- Dumped from database version 15.17
-- Dumped by pg_dump version 15.17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_announcement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_announcement (
    id bigint NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_posted boolean NOT NULL,
    course_id bigint NOT NULL,
    created_by_id bigint NOT NULL
);


--
-- Name: core_announcement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_announcement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_announcement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_course; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_course (
    id bigint NOT NULL,
    zoom_link text,
    course_name text NOT NULL,
    course_description text,
    score_total integer NOT NULL,
    ceu_act48_application_link text,
    ceu_credit_application_link text,
    ceu_program_evaluation_link text,
    student_enrollment_code character varying(20)
);


--
-- Name: core_course_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursetomodules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_coursetomodules (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    module_id bigint NOT NULL
);


--
-- Name: core_coursetomodules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_coursetomodules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursetomodules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursetostudents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_coursetostudents (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: core_coursetostudents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_coursetostudents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursetostudents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coursetoteachers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_coursetoteachers (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: core_coursetoteachers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_coursetoteachers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coursetoteachers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_module; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_module (
    id bigint NOT NULL,
    module_name text NOT NULL,
    module_description text,
    youtube_link text,
    module_order integer NOT NULL,
    score_total integer NOT NULL,
    is_posted boolean NOT NULL,
    course_id bigint NOT NULL,
    due_date timestamp with time zone
);


--
-- Name: core_module_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_module ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_module_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_moduletoquestions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_moduletoquestions (
    id bigint NOT NULL,
    module_id bigint NOT NULL,
    question_id bigint NOT NULL
);


--
-- Name: core_moduletoquestions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_moduletoquestions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_moduletoquestions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_question; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_question (
    id bigint NOT NULL,
    question_type character varying(20) NOT NULL,
    question_text text NOT NULL,
    mcq_options jsonb,
    question_order integer NOT NULL,
    score_total integer NOT NULL,
    module_id bigint NOT NULL
);


--
-- Name: core_question_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_questiontocorrectanswers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_questiontocorrectanswers (
    id bigint NOT NULL,
    correct_answer text NOT NULL,
    question_id bigint NOT NULL
);


--
-- Name: core_questiontocorrectanswers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_questiontocorrectanswers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_questiontocorrectanswers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_resource (
    id bigint NOT NULL,
    title text NOT NULL,
    description text,
    links jsonb NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL
);


--
-- Name: core_resource_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_resource ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_resource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_submission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_submission (
    id bigint NOT NULL,
    submission_type character varying(20) NOT NULL,
    submission_response text NOT NULL,
    time_submitted timestamp with time zone NOT NULL,
    module_id bigint NOT NULL,
    question_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: core_submission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_submission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    "isStudent" boolean NOT NULL
);


--
-- Name: core_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: core_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: core_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_usercoursegrade; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_usercoursegrade (
    id bigint NOT NULL,
    score integer,
    total integer,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: core_usercoursegrade_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_usercoursegrade ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_usercoursegrade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_usermodulegrade; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_usermodulegrade (
    id bigint NOT NULL,
    score integer,
    total integer,
    module_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: core_usermodulegrade_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_usermodulegrade ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_usermodulegrade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_userquestiongrade; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_userquestiongrade (
    id bigint NOT NULL,
    score double precision,
    total double precision,
    is_overdue boolean NOT NULL,
    question_id bigint NOT NULL,
    user_id bigint NOT NULL,
    teacher_comment text
);


--
-- Name: core_userquestiongrade_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_userquestiongrade ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_userquestiongrade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add course	7	add_course
26	Can change course	7	change_course
27	Can delete course	7	delete_course
28	Can view course	7	view_course
29	Can add course to students	8	add_coursetostudents
30	Can change course to students	8	change_coursetostudents
31	Can delete course to students	8	delete_coursetostudents
32	Can view course to students	8	view_coursetostudents
33	Can add course to teachers	9	add_coursetoteachers
34	Can change course to teachers	9	change_coursetoteachers
35	Can delete course to teachers	9	delete_coursetoteachers
36	Can view course to teachers	9	view_coursetoteachers
37	Can add module	10	add_module
38	Can change module	10	change_module
39	Can delete module	10	delete_module
40	Can view module	10	view_module
41	Can add course to modules	11	add_coursetomodules
42	Can change course to modules	11	change_coursetomodules
43	Can delete course to modules	11	delete_coursetomodules
44	Can view course to modules	11	view_coursetomodules
45	Can add question	12	add_question
46	Can change question	12	change_question
47	Can delete question	12	delete_question
48	Can view question	12	view_question
49	Can add module to questions	13	add_moduletoquestions
50	Can change module to questions	13	change_moduletoquestions
51	Can delete module to questions	13	delete_moduletoquestions
52	Can view module to questions	13	view_moduletoquestions
53	Can add question to correct answers	14	add_questiontocorrectanswers
54	Can change question to correct answers	14	change_questiontocorrectanswers
55	Can delete question to correct answers	14	delete_questiontocorrectanswers
56	Can view question to correct answers	14	view_questiontocorrectanswers
57	Can add submission	15	add_submission
58	Can change submission	15	change_submission
59	Can delete submission	15	delete_submission
60	Can view submission	15	view_submission
61	Can add user course grade	16	add_usercoursegrade
62	Can change user course grade	16	change_usercoursegrade
63	Can delete user course grade	16	delete_usercoursegrade
64	Can view user course grade	16	view_usercoursegrade
65	Can add user module grade	17	add_usermodulegrade
66	Can change user module grade	17	change_usermodulegrade
67	Can delete user module grade	17	delete_usermodulegrade
68	Can view user module grade	17	view_usermodulegrade
69	Can add user question grade	18	add_userquestiongrade
70	Can change user question grade	18	change_userquestiongrade
71	Can delete user question grade	18	delete_userquestiongrade
72	Can view user question grade	18	view_userquestiongrade
73	Can add announcement	19	add_announcement
74	Can change announcement	19	change_announcement
75	Can delete announcement	19	delete_announcement
76	Can view announcement	19	view_announcement
77	Can add resource	20	add_resource
78	Can change resource	20	change_resource
79	Can delete resource	20	delete_resource
80	Can view resource	20	view_resource
\.


--
-- Data for Name: core_announcement; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_announcement (id, title, content, created_at, is_posted, course_id, created_by_id) FROM stdin;
\.


--
-- Data for Name: core_course; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_course (id, zoom_link, course_name, course_description, score_total, ceu_act48_application_link, ceu_credit_application_link, ceu_program_evaluation_link, student_enrollment_code) FROM stdin;
1	https://upenn.zoom.us/j/2126678947	Fall 25	course	0	https://www.surveymonkey.com/r/231YAct48	https://www.surveymonkey.com/r/231Yapp	https://www.surveymonkey.com/r/231Yeval	FALL25
2	\N	Spring 26	\N	0	\N	\N	\N	\N
4	https://zoom.us/test	Course Testing	\N	0	\N	\N	\N	ROTSU
6	\N	Course Example	\N	0	\N	\N	\N	DAISP
\.


--
-- Data for Name: core_coursetomodules; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_coursetomodules (id, course_id, module_id) FROM stdin;
\.


--
-- Data for Name: core_coursetostudents; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_coursetostudents (id, course_id, user_id) FROM stdin;
8	4	20
9	6	21
\.


--
-- Data for Name: core_coursetoteachers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_coursetoteachers (id, course_id, user_id) FROM stdin;
4	4	18
6	6	18
\.


--
-- Data for Name: core_module; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_module (id, module_name, module_description, youtube_link, module_order, score_total, is_posted, course_id, due_date) FROM stdin;
16	Chapter 5 - Field Assignment	Description of the module		5	100	f	1	2026-01-31 05:00:00+00
80	Module 3 - How We Were Loved			3	100	f	6	\N
34	Module 6 - Connecting the Dots		https://youtu.be/DfqaxdeLcXA	6	100	f	4	2026-05-20 04:00:00+00
81	Module 4 - The Spectrum of Trauma		https://youtu.be/Pj4zjNdXHw0	4	100	f	6	\N
82	Field Assignment	Description of the module		5	100	f	6	\N
83	Module 6 - Connecting the Dots		https://youtu.be/DfqaxdeLcXA	6	100	f	6	\N
84	Module 7 - Post Traumatic Wisdom			7	100	f	6	\N
85	Module 8 - Relational Hunger	Chapter 9		8	100	f	6	\N
17	Chapter 6 - Connecting the Dots	Description of the module		6	100	f	1	2026-01-31 05:00:00+00
86	Module 9			9	100	f	6	\N
78	Module 1 - Making Sense of the World		https://youtube.com/shorts/sloq8nSdaMY	1	100	t	6	\N
79	Seeking Balance			2	100	t	6	\N
76	Module 9 - Relational Hunger			9	100	f	4	\N
32	Module 4 - The Spectrum of Trauma		https://youtu.be/Pj4zjNdXHw0	4	100	t	4	2026-05-30 04:00:00+00
18	Chapter 7 - Post Traumatic Wisdom	Description of the module		7	100	f	1	2026-01-31 05:00:00+00
35	Module 7 - Post Traumatic Wisdom			7	100	f	4	2026-05-30 04:00:00+00
29	Module 1 - Making Sense of the World		https://youtube.com/shorts/sloq8nSdaMY	1	100	t	4	2026-05-30 04:00:00+00
33	Field Assignment	Description of the module		5	100	t	4	2026-05-30 04:00:00+00
19	Chapter 9 - Relational Hunger	Description of the module		8	100	f	1	2026-01-31 05:00:00+00
12	Chapter 1 - Making Sense of the World		https://www.youtube.com/watch?v=Aw-xXOGjNSI	1	100	t	1	2026-01-31 05:00:00+00
13	Chapter 2 - Seeking Balance		https://www.youtube.com/watch?v=ZSyTOSztDmA	2	100	t	1	2026-01-31 05:00:00+00
20	Chapter 1 - Making Sense of the World		https://www.youtube.com/watch?v=Aw-xXOGjNSI	1	100	f	2	\N
21	Chapter 2 - Seeking Balance		https://www.youtube.com/watch?v=ZSyTOSztDmA	2	100	f	2	\N
22	Chapter 3 - How We Were Loved			3	100	f	2	\N
23	Chapter 4 - The Spectrum of Trauma			4	100	f	2	\N
24	Chapter 5 - Field Assignment	Description of the module		5	100	f	2	\N
25	Chapter 6 - Connecting the Dots	Description of the module		6	100	f	2	\N
26	Chapter 7 - Post Traumatic Wisdom	Description of the module		7	100	f	2	\N
27	Chapter 9 - Relational Hunger	Description of the module		8	100	f	2	\N
28	Module 9	Description of the module	\N	9	100	f	1	\N
14	Chapter 3 - How We Were Loved			3	100	t	1	2026-01-31 05:00:00+00
15	Chapter 4 - The Spectrum of Trauma			4	100	t	1	2026-01-31 05:00:00+00
75	Module 8 - Relational Hunger	Chapter 9		8	100	f	4	2026-05-30 04:00:00+00
30	Seeking Balance			2	100	t	4	2026-05-30 04:00:00+00
31	Module 3 - How We Were Loved			3	100	t	4	2026-05-20 04:00:00+00
\.


--
-- Data for Name: core_moduletoquestions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_moduletoquestions (id, module_id, question_id) FROM stdin;
\.


--
-- Data for Name: core_question; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_question (id, question_type, question_text, mcq_options, question_order, score_total, module_id) FROM stdin;
43	written	What is the difference between the “red brain” and the “blue brain,” and how can recognizing the difference improve your coaching?	[]	1	10	17
42	video	5 minutes\n\nTo build trust and peer recognition by encouraging players to identify who supported them during practice or daily life. This exercise strengthens team bonds and reinforces positive, trauma-informed connection.\n\nGather players into a circle after practice.\n\nCoach says:\n“We all get through tough moments because someone helps us along the way. Let’s recognize who had our back today.”\nOne by one, players call out or point to a teammate who supported them (in practice, at school, or in life).\nEncourage players to keep it short but specific (“Chris encouraged me when I was tired” / “Jamal helped me with homework”).\nClose the circle by thanking the team for seeing and supporting one another.\n\n“How did it feel to be recognized by a teammate?”\n“Why does it matter to know someone has your back?”\n“How can we show this same support off the field?”	[]	1	10	16
44	written	How can you adjust your communication based on whether a player is in red or blue brain state?	[]	2	10	17
47	written	What does Dr. Perry mean by "Emotional Catagion"?	[]	1	10	18
22	written	How does shifting from “What’s wrong with you?” to “What happened to you?” change the way you coach?	[]	1	10	12
23	written	Reflect on a time you misread a player’s behavior. How might Dr. Perry’s perspective have helped you respond differently?	[]	2	10	12
24	written	How can “making sense of the world” vary between athletes from different backgrounds? Give a real-life example.	[]	3	10	12
25	written	Describe one way you can build trust with your players by showing curiosity instead of judgment.	[]	4	10	12
26	written	Describe one insight from this week’s reading that changed or deepened your understanding of how people interpret their experiences.	[]	5	10	12
27	multiple_choice	During today’s session, how would you rate the overall emotional regulation of your players?	["A. Consistently calm and able to handle challenges without escalation", "B. Generally regulated with occasional moments of frustration or withdrawal", "C. Frequently dysregulated, showing noticeable stress, anger, or shutdown", "D. Predominantly dysregulated, unable to focus or engage in the activity"]	1	10	13
28	written	How does Dr. Perry describe the role of balance in emotional regulation, and how might this apply to athletes under pressure?	[]	2	10	13
29	written	Describe a situation where a player was “shaken” emotionally. How could you apply this week’s lesson to help them regulate?	[]	3	10	13
30	written	In the Water & Seltzer exercise, which behaviors or reactions do you think represent “water” and which represent “seltzer”? Explain why.	[]	4	10	13
31	written	How could you help your team collectively “seek balance” before a high-stakes game?	[]	5	10	13
32	written	Name 3 different types of Trauma	[]	6	10	13
33	written	Describe the definition of one of the traumas you wrote and give an example	[]	7	10	13
34	written	What connection does Dr. Perry make between early relationships and emotional regulation?	[]	1	10	14
35	written	Describe how building a safety plan for a player can improve both their performance and well-being.	[]	2	10	14
36	written	Think of an athlete you know — what might be two or three calming strategies that could go into their safety plan?	[]	3	10	14
37	written	How can you model healthy emotional regulation as a coach?	[]	4	10	14
48	written	How do we marginalize others trauma?	[]	2	10	18
38	written	How can understanding the “spectrum” of trauma help you coach more effectively?	[]	1	10	15
45	written	Think about a time a player was in “red brain” mode. How did you respond, and how might you respond differently now?	[]	3	10	17
40	written	Dr. Perry describes trauma as existing on a spectrum. How can recognizing that spectrum change the way you coach athletes with different life experiences?	[]	3	10	15
39	written	Describe how sports can serve as a healing space for players with different trauma histories.	[]	2	10	15
41	written	Think of a specific practice or game moment. How could you intentionally create space for athletes to feel both safe and supported, regardless of their trauma history?	[]	4	10	15
54	written	"The Collective" that Dr Perry speaks of is referring to what? Pg 249-250	[]	3	10	19
49	written	What does Dr. Perry say about dosing and how it benefits in coaching?	[]	3	10	18
46	written	After watching the HIM, describe one takeaway you can apply immediately in your coaching.	[]	4	10	17
52	written	How does relational hunger show up in your athletes, and how can you address it.	[]	1	10	19
50	written	Are children born resilent? If so how, If not why? "The book holds the answer"	[]	4	10	18
53	written	Dr Perry says "in order to best understand the here and now we need to know where we come from". What is your take on this?	[]	2	10	19
51	written	In what way does Dr. Perry speak about belonging as a means of healing	[]	5	10	18
57	written	How does shifting from “What’s wrong with you?” to “What happened to you?” change the way you coach?	[]	1	10	20
55	written	How does this collectiveness tie into mental health and children who have experienced trauma? Pg 258	[]	4	10	19
58	written	Reflect on a time you misread a player’s behavior. How might Dr. Perry’s perspective have helped you respond differently?	[]	2	10	20
56	written	What is Dr. Perry definition of empathy?	[]	5	10	19
59	written	How can “making sense of the world” vary between athletes from different backgrounds? Give a real-life example.	[]	3	10	20
60	written	Describe one way you can build trust with your players by showing curiosity instead of judgment.	[]	4	10	20
61	written	Describe one insight from this week’s reading that changed or deepened your understanding of how people interpret their experiences.	[]	5	10	20
62	multiple_choice	During today’s session, how would you rate the overall emotional regulation of your players?	["A. Consistently calm and able to handle challenges without escalation", "B. Generally regulated with occasional moments of frustration or withdrawal", "C. Frequently dysregulated, showing noticeable stress, anger, or shutdown", "D. Predominantly dysregulated, unable to focus or engage in the activity"]	1	10	21
63	written	How does Dr. Perry describe the role of balance in emotional regulation, and how might this apply to athletes under pressure?	[]	2	10	21
64	written	Describe a situation where a player was “shaken” emotionally. How could you apply this week’s lesson to help them regulate?	[]	3	10	21
65	written	In the Water & Seltzer exercise, which behaviors or reactions do you think represent “water” and which represent “seltzer”? Explain why.	[]	4	10	21
66	written	How could you help your team collectively “seek balance” before a high-stakes game?	[]	5	10	21
67	written	Name 3 different types of Trauma	[]	6	10	21
68	written	Describe the definition of one of the traumas you wrote and give an example	[]	7	10	21
69	written	What connection does Dr. Perry make between early relationships and emotional regulation?	[]	1	10	22
70	written	Describe how building a safety plan for a player can improve both their performance and well-being.	[]	2	10	22
71	written	Think of an athlete you know — what might be two or three calming strategies that could go into their safety plan?	[]	3	10	22
72	written	How can you model healthy emotional regulation as a coach?	[]	4	10	22
73	written	How can understanding the “spectrum” of trauma help you coach more effectively?	[]	1	10	23
74	written	Describe how sports can serve as a healing space for players with different trauma histories.	[]	2	10	23
75	written	Dr. Perry describes trauma as existing on a spectrum. How can recognizing that spectrum change the way you coach athletes with different life experiences?	[]	3	10	23
76	written	Think of a specific practice or game moment. How could you intentionally create space for athletes to feel both safe and supported, regardless of their trauma history?	[]	4	10	23
77	video	5 minutes\n\nTo build trust and peer recognition by encouraging players to identify who supported them during practice or daily life. This exercise strengthens team bonds and reinforces positive, trauma-informed connection.\n\nGather players into a circle after practice.\n\nCoach says:\n“We all get through tough moments because someone helps us along the way. Let’s recognize who had our back today.”\nOne by one, players call out or point to a teammate who supported them (in practice, at school, or in life).\nEncourage players to keep it short but specific (“Chris encouraged me when I was tired” / “Jamal helped me with homework”).\nClose the circle by thanking the team for seeing and supporting one another.\n\n“How did it feel to be recognized by a teammate?”\n“Why does it matter to know someone has your back?”\n“How can we show this same support off the field?”	[]	1	10	24
78	written	What is the difference between the “red brain” and the “blue brain,” and how can recognizing the difference improve your coaching?	[]	1	10	25
79	written	How can you adjust your communication based on whether a player is in red or blue brain state?	[]	2	10	25
80	written	Think about a time a player was in “red brain” mode. How did you respond, and how might you respond differently now?	[]	3	10	25
81	written	After watching the HIM, describe one takeaway you can apply immediately in your coaching.	[]	4	10	25
82	written	What does Dr. Perry mean by "Emotional Catagion"?	[]	1	10	26
83	written	How do we marginalize others trauma?	[]	2	10	26
84	written	What does Dr. Perry say about dosing and how it benefits in coaching?	[]	3	10	26
85	written	Are children born resilent? If so how, If not why? "The book holds the answer"	[]	4	10	26
86	written	In what way does Dr. Perry speak about belonging as a means of healing	[]	5	10	26
87	written	How does relational hunger show up in your athletes, and how can you address it.	[]	1	10	27
88	written	Dr Perry says "in order to best understand the here and now we need to know where we come from". What is your take on this?	[]	2	10	27
89	written	"The Collective" that Dr Perry speaks of is referring to what? Pg 249-250	[]	3	10	27
90	written	How does this collectiveness tie into mental health and children who have experienced trauma? Pg 258	[]	4	10	27
91	written	What is Dr. Perry definition of empathy?	[]	5	10	27
184	written	How does shifting from “What’s wrong with you?” to “What happened to you?” change the way you coach?	[]	1	10	78
93	written	Reflect on a time you misread a player’s behavior. How might Dr. Perry’s perspective have helped you respond differently?	[]	2	10	29
92	written	How does shifting from “What’s wrong with you?” to “What happened to you?” change the way you coach?	[]	1	10	29
95	written	Describe one way you can build trust with your players by showing curiosity instead of judgment.	[]	4	10	29
94	written	How can “making sense of the world” vary between athletes from different backgrounds? Give a real-life example.	[]	3	10	29
96	written	Describe one insight from this week’s reading that changed or deepened your understanding of how people interpret their experiences.	[]	5	10	29
185	written	Reflect on a time you misread a player’s behavior. How might Dr. Perry’s perspective have helped you respond differently?	[]	2	10	78
186	written	How can “making sense of the world” vary between athletes from different backgrounds? Give a real-life example.	[]	3	10	78
187	written	Describe one way you can build trust with your players by showing curiosity instead of judgment.	[]	4	10	78
188	written	Describe one insight from this week’s reading that changed or deepened your understanding of how people interpret their experiences.	[]	5	10	78
112	video	Gather players into a circle after practice.\n\nCoach says:\n“We all get through tough moments because someone helps us along the way. Let’s recognize who had our back today.”\n\nOne by one, players call out or point to a teammate who supported them (in practice, at school, or in life).\nEncourage players to keep it short but specific (“Chris encouraged me when I was tired” / “Jamal helped me with homework”).\nClose the circle by thanking the team for seeing and supporting one another.\n\n\n\n“How did it feel to be recognized by a teammate?”\n\n“Why does it matter to know someone has your back?”\n\n“How can we show this same support off the field?”	[]	1	10	33
98	written	How does Dr. Perry describe the role of balance in emotional regulation, and how might this apply to athletes under pressure?	[]	2	10	30
111	written	Think of a specific practice or game moment. How could you intentionally create space for athletes to feel both safe and supported, regardless of their trauma history?	[]	4	10	32
99	written	Describe a situation where a player was “shaken” emotionally. How could you apply this week’s lesson to help them regulate?	[]	3	10	30
100	written	In the Water & Seltzer exercise, which behaviors or reactions do you think represent “water” and which represent “seltzer”? Explain why.	[]	4	10	30
117	written	What does Dr. Perry mean by "Emotional Catagion"?	[]	1	10	35
189	multiple_choice	During today’s session, how would you rate the overall emotional regulation of your players?	["A. Consistently calm and able to handle challenges without escalation", "B. Generally regulated with occasional moments of frustration or withdrawal", "C. Frequently dysregulated, showing noticeable stress, anger, or shutdown", "D. Predominantly dysregulated, unable to focus or engage in the activity"]	1	10	79
101	written	How could you help your team collectively “seek balance” before a high-stakes game?	[]	5	10	30
119	written	How do we marginalize others trauma?	[]	2	10	35
102	written	Name 3 different types of Trauma	[]	6	10	30
97	multiple_choice	During today’s session, how would you rate the overall emotional regulation of your players?	["A. Consistently calm and able to handle challenges without escalation", "B. Generally regulated with occasional moments of frustration or withdrawal", "C. Frequently dysregulated, showing noticeable stress, anger, or shutdown", "D. Predominantly dysregulated, unable to focus or engage in the activity"]	1	10	30
103	written	Describe the definition of one of the traumas you wrote and give an example	[]	7	10	30
114	written	How can you adjust your communication based on whether a player is in red or blue brain state?	[]	2	10	34
104	written	What connection does Dr. Perry make between early relationships and emotional regulation?	[]	1	10	31
105	written	Describe how building a safety plan for a player can improve both their performance and well-being.	[]	2	10	31
118	written	What does Dr. Perry say about dosing and how it benefits in coaching?	[]	2	10	35
106	written	Think of an athlete you know — what might be two or three calming strategies that could go into their safety plan?	[]	3	10	31
115	written	Think about a time a player was in “red brain” mode. How did you respond, and how might you respond differently now?	[]	3	10	34
107	written	How can you model healthy emotional regulation as a coach?	[]	4	10	31
116	written	After watching the HIM , describe one takeaway you can apply immediately in your coaching.	[]	4	10	34
108	written	How can understanding the “spectrum” of trauma help you coach more effectively?	[]	1	10	32
190	written	How does Dr. Perry describe the role of balance in emotional regulation, and how might this apply to athletes under pressure?	[]	2	10	79
113	written	What is the difference between the “red brain” and the “blue brain,” and how can recognizing the difference improve your coaching?	[]	1	10	34
191	written	Describe a situation where a player was “shaken” emotionally. How could you apply this week’s lesson to help them regulate?	[]	3	10	79
110	written	Dr. Perry describes trauma as existing on a spectrum. How can recognizing that spectrum change the way you coach athletes with different life experiences?	[]	3	10	32
120	written	Are children born resilent? If so how, If not why? "The book holds the answer"	[]	3	10	35
109	written	Describe how sports can serve as a healing space for players with different trauma histories.	[]	2	10	32
192	written	In the Water & Seltzer exercise, which behaviors or reactions do you think represent “water” and which represent “seltzer”? Explain why.	[]	4	10	79
121	written	In what way does Dr. Perry speak about belonging as a means of healing	[]	4	10	35
193	written	How could you help your team collectively “seek balance” before a high-stakes game?	[]	5	10	79
194	written	Name 3 different types of Trauma	[]	6	10	79
195	written	Describe the definition of one of the traumas you wrote and give an example	[]	7	10	79
196	written	What connection does Dr. Perry make between early relationships and emotional regulation?	[]	1	10	80
197	written	Describe how building a safety plan for a player can improve both their performance and well-being.	[]	2	10	80
198	written	Think of an athlete you know — what might be two or three calming strategies that could go into their safety plan?	[]	3	10	80
199	written	How can you model healthy emotional regulation as a coach?	[]	4	10	80
200	written	How can understanding the “spectrum” of trauma help you coach more effectively?	[]	1	10	81
201	written	Describe how sports can serve as a healing space for players with different trauma histories.	[]	2	10	81
202	written	Dr. Perry describes trauma as existing on a spectrum. How can recognizing that spectrum change the way you coach athletes with different life experiences?	[]	3	10	81
203	written	Think of a specific practice or game moment. How could you intentionally create space for athletes to feel both safe and supported, regardless of their trauma history?	[]	4	10	81
204	video	Gather players into a circle after practice.\n\nCoach says:\n“We all get through tough moments because someone helps us along the way. Let’s recognize who had our back today.”\n\nOne by one, players call out or point to a teammate who supported them (in practice, at school, or in life).\nEncourage players to keep it short but specific (“Chris encouraged me when I was tired” / “Jamal helped me with homework”).\nClose the circle by thanking the team for seeing and supporting one another.\n\n\n\n“How did it feel to be recognized by a teammate?”\n\n“Why does it matter to know someone has your back?”\n\n“How can we show this same support off the field?”	[]	1	10	82
205	written	What is the difference between the “red brain” and the “blue brain,” and how can recognizing the difference improve your coaching?	[]	1	10	83
206	written	How can you adjust your communication based on whether a player is in red or blue brain state?	[]	2	10	83
207	written	Think about a time a player was in “red brain” mode. How did you respond, and how might you respond differently now?	[]	3	10	83
208	written	After watching the HIM , describe one takeaway you can apply immediately in your coaching.	[]	4	10	83
209	written	What does Dr. Perry mean by "Emotional Catagion"?	[]	1	10	84
210	written	How do we marginalize others trauma?	[]	2	10	84
211	written	What does Dr. Perry say about dosing and how it benefits in coaching?	[]	2	10	84
212	written	Are children born resilent? If so how, If not why? "The book holds the answer"	[]	3	10	84
213	written	In what way does Dr. Perry speak about belonging as a means of healing	[]	4	10	84
214	written	How does relational hunger show up in your athletes, and how can you address it.	[]	1	10	85
215	written	Dr Perry says "in order to best understand the here and now we need to know where we come from". What is your take on this?	[]	2	10	85
216	multiple_choice	How does relational hunger show up in your athletes, and how can you address it.	[""]	1	10	86
217	written	New Question	[]	2	10	86
218	written	"The Collective" that Dr Perry speaks of is referring to what? Pg 249-250	[]	3	10	86
176	written	How does relational hunger show up in your athletes, and how can you address it.	[]	1	10	75
219	written	How does this collectivesness tie into mental health and children who have experienced trauma? Pg 258	[]	4	10	86
177	written	Dr Perry says "in order to best understand the here and now we need to know where we come from". What is your take on this?	[]	2	10	75
220	written	What is Dr. Perry definition of empathy?	[]	5	10	86
178	multiple_choice	How does relational hunger show up in your athletes, and how can you address it.	[""]	1	10	76
180	written	New Question	[]	2	10	76
181	written	"The Collective" that Dr Perry speaks of is referring to what? Pg 249-250	[]	3	10	76
182	written	How does this collectivesness tie into mental health and children who have experienced trauma? Pg 258	[]	4	10	76
183	written	What is Dr. Perry definition of empathy?	[]	5	10	76
\.


--
-- Data for Name: core_questiontocorrectanswers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_questiontocorrectanswers (id, correct_answer, question_id) FROM stdin;
4	A. Consistently calm and able to handle challenges without escalation	97
5	A. Consistently calm and able to handle challenges without escalation	97
6	A. Consistently calm and able to handle challenges without escalation	189
7	A. Consistently calm and able to handle challenges without escalation	189
\.


--
-- Data for Name: core_resource; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_resource (id, title, description, links, "order", created_at, course_id) FROM stdin;
1	CEU Links	The Office of Education and Consultative Services is committed to providing high quality training and ample opportunities for continuing education. Please visit the following links to apply for continuing education credits and evaluating the program.	[{"url": "https://www.surveymonkey.com/r/231Yapp", "label": "ACT 48 Application"}, {"url": "https://www.surveymonkey.com/r/231YAct48", "label": "Continuing Education Credit Application"}, {"url": "https://www.surveymonkey.com/r/231Yeval", "label": "Program Evaluation"}]	0	2026-03-30 17:56:01.556891+00	4
3	Catagories of Trauma that People Experience	\N	[{"url": "http://localhost:8000/media/resource_pdfs/500de3d51aa146599283ed47c30369e3.pdf", "kind": "pdf", "label": "Types of Trauma"}]	1	2026-04-10 07:14:55.450395+00	4
\.


--
-- Data for Name: core_submission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_submission (id, submission_type, submission_response, time_submitted, module_id, question_id, user_id) FROM stdin;
122	written	test	2026-04-10 06:25:28.31003+00	29	94	20
121	written	test	2026-04-10 06:25:28.309652+00	29	93	20
124	written	test	2026-04-10 06:25:28.311596+00	29	96	20
123	written	test	2026-04-10 06:25:28.311183+00	29	95	20
125	written	test	2026-04-10 06:25:28.311996+00	29	92	20
127	written	test	2026-04-10 06:25:49.09873+00	30	98	20
126	written	test	2026-04-10 06:25:49.097244+00	30	99	20
128	multiple_choice	C. Frequently dysregulated, showing noticeable stress, anger, or shutdown	2026-04-10 06:25:49.099089+00	30	97	20
129	written	test	2026-04-10 06:25:49.100721+00	30	100	20
130	written	test	2026-04-10 06:25:49.101192+00	30	101	20
131	written	test	2026-04-10 06:25:49.101599+00	30	102	20
132	written	test	2026-04-10 06:25:49.144776+00	30	103	20
134	written	e	2026-04-10 07:29:34.460988+00	31	107	20
133	written	e	2026-04-10 07:29:34.459882+00	31	104	20
135	written	e	2026-04-10 07:29:34.521141+00	31	106	20
136	written	e	2026-04-10 07:29:34.520984+00	31	105	20
137	written	e	2026-04-10 07:29:51.419333+00	32	110	20
138	written	e	2026-04-10 07:29:51.419814+00	32	108	20
139	written	e	2026-04-10 07:29:51.421649+00	32	109	20
140	written	e	2026-04-10 07:29:51.424054+00	32	111	20
\.


--
-- Data for Name: core_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, "isStudent") FROM stdin;
18	pbkdf2_sha256$1000000$ua53FTeS2axWrVGOXbJJdN$gUMWW4zlvFsP7gsiP6piS2KXmtPHRs7B20DdBW8CgP0=	\N	f	odaapinc@gmail.com	Valencia	Peterson	odaapinc@gmail.com	f	t	2026-03-30 17:04:51.143846+00	f
20	pbkdf2_sha256$1000000$a5NZa2bCzhXqRBCpFhYOQ3$Y/GtCizYP9tX11Ylxzt/CrdvrRn5zd9q1qZrdsir2E8=	\N	f	student@gmail.com	Student	Example	student@gmail.com	f	t	2026-04-10 06:24:27.32149+00	t
21	pbkdf2_sha256$1000000$st7qHpHBRA4UkBlrnRKxtn$2w1f03ODxfVEFUx4qt2yFK7DtY5hp/cgDq/f79YV/ZI=	\N	f	stu@gmail.com	Student	Example	stu@gmail.com	f	t	2026-04-10 06:34:08.89294+00	t
\.


--
-- Data for Name: core_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: core_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: core_usercoursegrade; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_usercoursegrade (id, score, total, course_id, user_id) FROM stdin;
\.


--
-- Data for Name: core_usermodulegrade; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_usermodulegrade (id, score, total, module_id, user_id) FROM stdin;
\.


--
-- Data for Name: core_userquestiongrade; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_userquestiongrade (id, score, total, is_overdue, question_id, user_id, teacher_comment) FROM stdin;
17	0	1	f	97	20	\N
22	1	1	f	102	20	\N
19	0.2	1	f	100	20	\N
18	0.7	1	f	101	20	\N
20	1	1	f	98	20	\N
21	0.9	1	f	99	20	\N
23	0.3	1	f	103	20	\N
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	core	user
7	core	course
8	core	coursetostudents
9	core	coursetoteachers
10	core	module
11	core	coursetomodules
12	core	question
13	core	moduletoquestions
14	core	questiontocorrectanswers
15	core	submission
16	core	usercoursegrade
17	core	usermodulegrade
18	core	userquestiongrade
19	core	announcement
20	core	resource
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-11-20 01:43:52.799389+00
2	contenttypes	0002_remove_content_type_name	2025-11-20 01:43:52.80603+00
3	auth	0001_initial	2025-11-20 01:43:52.859563+00
4	auth	0002_alter_permission_name_max_length	2025-11-20 01:43:52.864028+00
5	auth	0003_alter_user_email_max_length	2025-11-20 01:43:52.867344+00
6	auth	0004_alter_user_username_opts	2025-11-20 01:43:52.871921+00
7	auth	0005_alter_user_last_login_null	2025-11-20 01:43:52.876246+00
8	auth	0006_require_contenttypes_0002	2025-11-20 01:43:52.878938+00
9	auth	0007_alter_validators_add_error_messages	2025-11-20 01:43:52.886402+00
10	auth	0008_alter_user_username_max_length	2025-11-20 01:43:52.893213+00
11	auth	0009_alter_user_last_name_max_length	2025-11-20 01:43:52.898136+00
12	auth	0010_alter_group_name_max_length	2025-11-20 01:43:52.903126+00
13	auth	0011_update_proxy_permissions	2025-11-20 01:43:52.906344+00
14	auth	0012_alter_user_first_name_max_length	2025-11-20 01:43:52.909954+00
15	core	0001_initial	2025-11-20 01:43:52.9417+00
16	admin	0001_initial	2025-11-20 01:43:52.957719+00
17	admin	0002_logentry_remove_auto_add	2025-11-20 01:43:52.961404+00
18	admin	0003_logentry_add_action_flag_choices	2025-11-20 01:43:52.966318+00
19	sessions	0001_initial	2025-11-20 01:43:52.975709+00
20	core	0002_course_user_isstudent_coursetostudents_and_more	2025-12-02 21:17:30.565+00
21	core	0003_alter_course_options_alter_coursetomodules_options_and_more	2025-12-02 23:13:27.635065+00
22	core	0004_announcement	2025-12-04 00:47:25.229472+00
23	core	0005_course_ceu_act48_application_link_and_more	2025-12-23 22:05:57.021992+00
24	core	0006_course_student_enrollment_code	2026-01-09 21:14:39.09693+00
25	core	0007_userquestiongrade_score_total_float_teacher_comment	2026-01-09 22:05:18.273998+00
26	core	0008_resource	2026-03-30 17:42:54.643596+00
27	core	0009_course_meeting_schedule	2026-04-09 21:15:33.237055+00
28	core	0010_remove_course_meeting_schedule	2026-04-10 07:23:40.501416+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
cprdy7xvlcmcapumcm3eqlafknbw52p9	.eJxVjMsOwiAQAP-FsyHyBo_e_Qayu2ylamhS2pPx3w1JD3qdmcxbZNi3mvfOa56LuIgkTr8MgZ7chigPaPdF0tK2dUY5EnnYLm9L4df1aP8GFXod27NjRQzG2hiQndbGo2YVnQomEk0-BQATUXGJKkAim6INAe3kyIIXny_WmTeN:1vQZNl:4T3aCPwspmo3Qc5P4BPAo4JAXcVEBT7Fw9YfRbbV9kU	2025-12-16 23:02:05.952805+00
nw92o53ls59stdd73rowwprmd12yvnft	.eJxVjDsOwjAQBe_iGll28JeSnjNYu941DiBHipMKcXcSKQW0b2beWyRYl5rWznMaSVyE9uL0OyLkJ7ed0APafZJ5ass8otwVedAubxPx63q4fwcVet1qWzw4jYMJmVz0g1JFeQ3GWb8RdIXOxka2QIY4MioM0YSgQo6as4ni8wUAADf0:1w7G1f:j6cbDEfRbct7cJe2yItVkwjNKw-CVci3z-2fuKnA5pQ	2026-04-13 17:03:43.632116+00
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- Name: core_announcement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_announcement_id_seq', 15, true);


--
-- Name: core_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_course_id_seq', 6, true);


--
-- Name: core_coursetomodules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_coursetomodules_id_seq', 1, false);


--
-- Name: core_coursetostudents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_coursetostudents_id_seq', 9, true);


--
-- Name: core_coursetoteachers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_coursetoteachers_id_seq', 6, true);


--
-- Name: core_module_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_module_id_seq', 87, true);


--
-- Name: core_moduletoquestions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_moduletoquestions_id_seq', 3, true);


--
-- Name: core_question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_question_id_seq', 221, true);


--
-- Name: core_questiontocorrectanswers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_questiontocorrectanswers_id_seq', 7, true);


--
-- Name: core_resource_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_resource_id_seq', 3, true);


--
-- Name: core_submission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_submission_id_seq', 140, true);


--
-- Name: core_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_user_groups_id_seq', 1, false);


--
-- Name: core_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_user_id_seq', 21, true);


--
-- Name: core_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_user_user_permissions_id_seq', 1, false);


--
-- Name: core_usercoursegrade_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_usercoursegrade_id_seq', 1, false);


--
-- Name: core_usermodulegrade_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_usermodulegrade_id_seq', 1, false);


--
-- Name: core_userquestiongrade_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_userquestiongrade_id_seq', 23, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 48, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 28, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: core_announcement core_announcement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_announcement
    ADD CONSTRAINT core_announcement_pkey PRIMARY KEY (id);


--
-- Name: core_course core_course_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_course
    ADD CONSTRAINT core_course_pkey PRIMARY KEY (id);


--
-- Name: core_course core_course_student_enrollment_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_course
    ADD CONSTRAINT core_course_student_enrollment_code_key UNIQUE (student_enrollment_code);


--
-- Name: core_coursetomodules core_coursetomodules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_coursetomodules
    ADD CONSTRAINT core_coursetomodules_pkey PRIMARY KEY (id);


--
-- Name: core_coursetostudents core_coursetostudents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_coursetostudents
    ADD CONSTRAINT core_coursetostudents_pkey PRIMARY KEY (id);


--
-- Name: core_coursetoteachers core_coursetoteachers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_coursetoteachers
    ADD CONSTRAINT core_coursetoteachers_pkey PRIMARY KEY (id);


--
-- Name: core_module core_module_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_module
    ADD CONSTRAINT core_module_pkey PRIMARY KEY (id);


--
-- Name: core_moduletoquestions core_moduletoquestions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_moduletoquestions
    ADD CONSTRAINT core_moduletoquestions_pkey PRIMARY KEY (id);


--
-- Name: core_question core_question_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_question
    ADD CONSTRAINT core_question_pkey PRIMARY KEY (id);


--
-- Name: core_questiontocorrectanswers core_questiontocorrectanswers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_questiontocorrectanswers
    ADD CONSTRAINT core_questiontocorrectanswers_pkey PRIMARY KEY (id);


--
-- Name: core_resource core_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_resource
    ADD CONSTRAINT core_resource_pkey PRIMARY KEY (id);


--
-- Name: core_submission core_submission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_submission
    ADD CONSTRAINT core_submission_pkey PRIMARY KEY (id);


--
-- Name: core_user_groups core_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_user_groups
    ADD CONSTRAINT core_user_groups_pkey PRIMARY KEY (id);


--
-- Name: core_user_groups core_user_groups_user_id_group_id_c82fcad1_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_user_groups
    ADD CONSTRAINT core_user_groups_user_id_group_id_c82fcad1_uniq UNIQUE (user_id, group_id);


--
-- Name: core_user core_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_user
    ADD CONSTRAINT core_user_pkey PRIMARY KEY (id);


--
-- Name: core_user_user_permissions core_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_user_user_permissions
    ADD CONSTRAINT core_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: core_user_user_permissions core_user_user_permissions_user_id_permission_id_73ea0daa_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_user_user_permissions
    ADD CONSTRAINT core_user_user_permissions_user_id_permission_id_73ea0daa_uniq UNIQUE (user_id, permission_id);


--
-- Name: core_user core_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_user
    ADD CONSTRAINT core_user_username_key UNIQUE (username);


--
-- Name: core_usercoursegrade core_usercoursegrade_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_usercoursegrade
    ADD CONSTRAINT core_usercoursegrade_pkey PRIMARY KEY (id);


--
-- Name: core_usermodulegrade core_usermodulegrade_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_usermodulegrade
    ADD CONSTRAINT core_usermodulegrade_pkey PRIMARY KEY (id);


--
-- Name: core_userquestiongrade core_userquestiongrade_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_userquestiongrade
    ADD CONSTRAINT core_userquestiongrade_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: core_announcement_course_id_e8b61541; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_announcement_course_id_e8b61541 ON public.core_announcement USING btree (course_id);


--
-- Name: core_announcement_created_by_id_86b3e573; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_announcement_created_by_id_86b3e573 ON public.core_announcement USING btree (created_by_id);


--
-- Name: core_course_student_enrollment_code_23a74063_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_course_student_enrollment_code_23a74063_like ON public.core_course USING btree (student_enrollment_code varchar_pattern_ops);


--
-- Name: core_coursetomodules_course_id_0360b9e5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_coursetomodules_course_id_0360b9e5 ON public.core_coursetomodules USING btree (course_id);


--
-- Name: core_coursetomodules_module_id_563a5cd8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_coursetomodules_module_id_563a5cd8 ON public.core_coursetomodules USING btree (module_id);


--
-- Name: core_coursetostudents_course_id_f12ab853; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_coursetostudents_course_id_f12ab853 ON public.core_coursetostudents USING btree (course_id);


--
-- Name: core_coursetostudents_user_id_d5e1f6fe; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_coursetostudents_user_id_d5e1f6fe ON public.core_coursetostudents USING btree (user_id);


--
-- Name: core_coursetoteachers_course_id_d6abde6f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_coursetoteachers_course_id_d6abde6f ON public.core_coursetoteachers USING btree (course_id);


--
-- Name: core_coursetoteachers_user_id_509d636b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_coursetoteachers_user_id_509d636b ON public.core_coursetoteachers USING btree (user_id);


--
-- Name: core_module_course_id_2aa5c263; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_module_course_id_2aa5c263 ON public.core_module USING btree (course_id);


--
-- Name: core_moduletoquestions_module_id_56250a65; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_moduletoquestions_module_id_56250a65 ON public.core_moduletoquestions USING btree (module_id);


--
-- Name: core_moduletoquestions_question_id_0909624f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_moduletoquestions_question_id_0909624f ON public.core_moduletoquestions USING btree (question_id);


--
-- Name: core_question_module_id_b83d8387; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_question_module_id_b83d8387 ON public.core_question USING btree (module_id);


--
-- Name: core_questiontocorrectanswers_question_id_fecc76b3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_questiontocorrectanswers_question_id_fecc76b3 ON public.core_questiontocorrectanswers USING btree (question_id);


--
-- Name: core_resource_course_id_ff221a17; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_resource_course_id_ff221a17 ON public.core_resource USING btree (course_id);


--
-- Name: core_submission_module_id_bf18d995; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_submission_module_id_bf18d995 ON public.core_submission USING btree (module_id);


--
-- Name: core_submission_question_id_015f02f3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_submission_question_id_015f02f3 ON public.core_submission USING btree (question_id);


--
-- Name: core_submission_user_id_b062d25d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_submission_user_id_b062d25d ON public.core_submission USING btree (user_id);


--
-- Name: core_user_groups_group_id_fe8c697f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_user_groups_group_id_fe8c697f ON public.core_user_groups USING btree (group_id);


--
-- Name: core_user_groups_user_id_70b4d9b8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_user_groups_user_id_70b4d9b8 ON public.core_user_groups USING btree (user_id);


--
-- Name: core_user_user_permissions_permission_id_35ccf601; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_user_user_permissions_permission_id_35ccf601 ON public.core_user_user_permissions USING btree (permission_id);


--
-- Name: core_user_user_permissions_user_id_085123d3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_user_user_permissions_user_id_085123d3 ON public.core_user_user_permissions USING btree (user_id);


--
-- Name: core_user_username_36e4f7f7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_user_username_36e4f7f7_like ON public.core_user USING btree (username varchar_pattern_ops);


--
-- Name: core_usercoursegrade_course_id_ce876cc8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_usercoursegrade_course_id_ce876cc8 ON public.core_usercoursegrade USING btree (course_id);


--
-- Name: core_usercoursegrade_user_id_dbaa2777; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_usercoursegrade_user_id_dbaa2777 ON public.core_usercoursegrade USING btree (user_id);


--
-- Name: core_usermodulegrade_module_id_32b91e2f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_usermodulegrade_module_id_32b91e2f ON public.core_usermodulegrade USING btree (module_id);


--
-- Name: core_usermodulegrade_user_id_7affd70e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_usermodulegrade_user_id_7affd70e ON public.core_usermodulegrade USING btree (user_id);


--
-- Name: core_userquestiongrade_question_id_4377fff8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_userquestiongrade_question_id_4377fff8 ON public.core_userquestiongrade USING btree (question_id);


--
-- Name: core_userquestiongrade_user_id_eb8e5685; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_userquestiongrade_user_id_eb8e5685 ON public.core_userquestiongrade USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_announcement core_announcement_course_id_e8b61541_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_announcement
    ADD CONSTRAINT core_announcement_course_id_e8b61541_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_announcement core_announcement_created_by_id_86b3e573_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_announcement
    ADD CONSTRAINT core_announcement_created_by_id_86b3e573_fk_core_user_id FOREIGN KEY (created_by_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursetomodules core_coursetomodules_course_id_0360b9e5_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_coursetomodules
    ADD CONSTRAINT core_coursetomodules_course_id_0360b9e5_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursetomodules core_coursetomodules_module_id_563a5cd8_fk_core_module_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_coursetomodules
    ADD CONSTRAINT core_coursetomodules_module_id_563a5cd8_fk_core_module_id FOREIGN KEY (module_id) REFERENCES public.core_module(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursetostudents core_coursetostudents_course_id_f12ab853_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_coursetostudents
    ADD CONSTRAINT core_coursetostudents_course_id_f12ab853_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursetostudents core_coursetostudents_user_id_d5e1f6fe_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_coursetostudents
    ADD CONSTRAINT core_coursetostudents_user_id_d5e1f6fe_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursetoteachers core_coursetoteachers_course_id_d6abde6f_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_coursetoteachers
    ADD CONSTRAINT core_coursetoteachers_course_id_d6abde6f_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_coursetoteachers core_coursetoteachers_user_id_509d636b_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_coursetoteachers
    ADD CONSTRAINT core_coursetoteachers_user_id_509d636b_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_module core_module_course_id_2aa5c263_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_module
    ADD CONSTRAINT core_module_course_id_2aa5c263_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_moduletoquestions core_moduletoquestions_module_id_56250a65_fk_core_module_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_moduletoquestions
    ADD CONSTRAINT core_moduletoquestions_module_id_56250a65_fk_core_module_id FOREIGN KEY (module_id) REFERENCES public.core_module(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_moduletoquestions core_moduletoquestions_question_id_0909624f_fk_core_question_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_moduletoquestions
    ADD CONSTRAINT core_moduletoquestions_question_id_0909624f_fk_core_question_id FOREIGN KEY (question_id) REFERENCES public.core_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_question core_question_module_id_b83d8387_fk_core_module_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_question
    ADD CONSTRAINT core_question_module_id_b83d8387_fk_core_module_id FOREIGN KEY (module_id) REFERENCES public.core_module(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_questiontocorrectanswers core_questiontocorre_question_id_fecc76b3_fk_core_ques; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_questiontocorrectanswers
    ADD CONSTRAINT core_questiontocorre_question_id_fecc76b3_fk_core_ques FOREIGN KEY (question_id) REFERENCES public.core_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_resource core_resource_course_id_ff221a17_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_resource
    ADD CONSTRAINT core_resource_course_id_ff221a17_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_submission core_submission_module_id_bf18d995_fk_core_module_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_submission
    ADD CONSTRAINT core_submission_module_id_bf18d995_fk_core_module_id FOREIGN KEY (module_id) REFERENCES public.core_module(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_submission core_submission_question_id_015f02f3_fk_core_question_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_submission
    ADD CONSTRAINT core_submission_question_id_015f02f3_fk_core_question_id FOREIGN KEY (question_id) REFERENCES public.core_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_submission core_submission_user_id_b062d25d_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_submission
    ADD CONSTRAINT core_submission_user_id_b062d25d_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_user_groups core_user_groups_group_id_fe8c697f_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_user_groups
    ADD CONSTRAINT core_user_groups_group_id_fe8c697f_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_user_groups core_user_groups_user_id_70b4d9b8_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_user_groups
    ADD CONSTRAINT core_user_groups_user_id_70b4d9b8_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_user_user_permissions core_user_user_permi_permission_id_35ccf601_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_user_user_permissions
    ADD CONSTRAINT core_user_user_permi_permission_id_35ccf601_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_user_user_permissions core_user_user_permissions_user_id_085123d3_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_user_user_permissions
    ADD CONSTRAINT core_user_user_permissions_user_id_085123d3_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_usercoursegrade core_usercoursegrade_course_id_ce876cc8_fk_core_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_usercoursegrade
    ADD CONSTRAINT core_usercoursegrade_course_id_ce876cc8_fk_core_course_id FOREIGN KEY (course_id) REFERENCES public.core_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_usercoursegrade core_usercoursegrade_user_id_dbaa2777_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_usercoursegrade
    ADD CONSTRAINT core_usercoursegrade_user_id_dbaa2777_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_usermodulegrade core_usermodulegrade_module_id_32b91e2f_fk_core_module_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_usermodulegrade
    ADD CONSTRAINT core_usermodulegrade_module_id_32b91e2f_fk_core_module_id FOREIGN KEY (module_id) REFERENCES public.core_module(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_usermodulegrade core_usermodulegrade_user_id_7affd70e_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_usermodulegrade
    ADD CONSTRAINT core_usermodulegrade_user_id_7affd70e_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_userquestiongrade core_userquestiongrade_question_id_4377fff8_fk_core_question_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_userquestiongrade
    ADD CONSTRAINT core_userquestiongrade_question_id_4377fff8_fk_core_question_id FOREIGN KEY (question_id) REFERENCES public.core_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_userquestiongrade core_userquestiongrade_user_id_eb8e5685_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_userquestiongrade
    ADD CONSTRAINT core_userquestiongrade_user_id_eb8e5685_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_core_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_core_user_id FOREIGN KEY (user_id) REFERENCES public.core_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict SwlyxFxAiUt4GvrK6J2wgiCa7i6S1zHAYScdfKD54DomabNUBIKr4cpbNn91JWM

