# Generated by Django 5.2.8 on 2025-12-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_user_isstudent_coursetostudents_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursetomodules',
            options={'verbose_name_plural': 'Course to Modules'},
        ),
        migrations.AlterModelOptions(
            name='coursetostudents',
            options={'verbose_name_plural': 'Course to Students'},
        ),
        migrations.AlterModelOptions(
            name='coursetoteachers',
            options={'verbose_name_plural': 'Course to Teachers'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='moduletoquestions',
            options={'verbose_name_plural': 'Module to Questions'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questiontocorrectanswers',
            options={'verbose_name_plural': 'Question to Correct Answers'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name_plural': 'Submissions'},
        ),
        migrations.AddField(
            model_name='module',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
