# Generated by Django 5.2.8 on 2025-12-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ceu_act48_application_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ceu_credit_application_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ceu_program_evaluation_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
