# Generated by Django 5.2.8 on 2026-04-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meeting_schedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
